[technote]
id = "DMTN-320"
series_id = "DMTN"
canonical_url = "https://dmtn-320.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-320"
github_default_branch = "main"
date_created = 2025-06-11T20:59:05Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Ross"
name.family = "Ceballo"
internal_id = "ceballor"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory/NSF NOIRLab"
internal_id = "RubinOps"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
